Repository kevin-nca/netgrade, pull requests merged in 2025-09, with the labels that each got.

#165 feat(AddGradePage): auto-fill school and subject when adding a grade
  src/pages/home/grades/AddGradePage.tsx
  src/pages/home/grades/GradeEntryPage.tsx
Labels: feature

#117 feat: sort the exams by date
  src/hooks/queries/useExamQueries.ts
  src/pages/home/HomePage.css
  src/pages/home/HomePage.tsx
  src/services/ExamService.ts
Labels: enhancement, style

#129 fix: bottom navigation bar should only be visible on main pages
  src/components/bottom-navigation/bottom-navigation.tsx
  src/pages/home/HomePage.tsx
  src/pages/home/calendar/CalendarPage.tsx
  src/pages/home/grades/AddGradePage.tsx
  src/pages/home/settings/SettingsPage.tsx
Labels: feature

#174 ci: display test coverage
  .github/workflows/ci.yml
  README.md
  codecov.yml
  package-lock.json
  package.json
  vite.config.ts
Labels: codex

#192 fix: the grades are now visible on light mode
  src/pages/home/school/SchoolPage.css
Labels: bug

#191 fix: adjust bottom spacer height for better layout consistency
  src/pages/home/HomePage.css
Labels: bug

#198 feat: add dark mode support for "Export Data" popup
  src/components/export/ExportDialog.css
  src/components/export/ExportDialog.tsx
Labels: style

#120 style: changed the CSS so that the settings title is centered
  src/pages/home/settings/SettingsPage.css
Labels: style

#171 feat: show subject.name as title in GradeEntryPage
  src/hooks/queries/useGradeQueries.ts
  src/pages/home/grades/GradeEntryPage.tsx
  src/services/GradeService.ts
  src/tests/services/GradeService.test.ts
Labels: style
