Repository kevin-nca/netgrade, pull requests merged in 2025-06, with the labels that each got.

#49 fix: improve iOS pipeline
  .github/workflows/release.yml
  fastlane/Fastfile
  ios/App/App/Info.plist
Labels: feature

#47 feat: Redesign EditExamPage with improved UX and modular components
  package-lock.json
  package.json
  src/AppRouter.tsx
  src/components/Form/validated-number-input/validatedNumberInput.tsx
  src/pages/home/exams/EditExamPage.tsx
  src/pages/home/exams/EditExamPage/EditExamPage.module.css
  src/pages/home/exams/EditExamPage/EditExamPage.tsx
  src/pages/home/exams/EditExamPage/components/ExamDetailsForm.tsx
  src/pages/home/exams/EditExamPage/components/GradeForm.tsx
  src/pages/home/exams/EditExamPage/styles/FormCommon.module.css
  src/pages/home/exams/EditExamPage/styles/GradeForm.module.css
  src/pages/home/exams/EditExamPage/types.ts
  src/pages/home/exams/EditExamPage/utils.ts
  src/utils/validation.ts
Labels: enhancement

#52 fix: Redirect to onboarding after data reset
  src/pages/home/settings/SettingsPage.tsx
Labels: bug

#59 fix: prevent jumping buttons
  src/pages/home/HomePage.tsx
  src/pages/onboarding/steps/NameStep.tsx
  src/pages/onboarding/steps/SchoolStep.tsx
Labels: bug

#60 feat(layout): wrap all step pages in shared Layout component
  src/pages/home/HomePage.tsx
  src/pages/onboarding/steps/NameStep.tsx
  src/pages/onboarding/steps/SchoolStep.tsx
Labels: feature

#62 Onboarding UI: Centered fields and buttons, unified colors, single-co…
  src/components/Form/FormField.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/steps/NameStep.module.css
  src/pages/onboarding/steps/NameStep.tsx
  src/pages/onboarding/steps/SchoolStep.module.css
  src/pages/onboarding/steps/SchoolStep.tsx
  src/pages/onboarding/steps/SubjectStep.module.css
  src/pages/onboarding/steps/SubjectStep.tsx
Labels: feature
