Repository kevin-nca/netgrade, pull requests merged in 2025-05, with the labels that each got.

#22 chore(capacitor): migrate project to Capacitor 7
  .github/workflows/ci.yml
  .github/workflows/release.yml
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/variables.gradle
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/Podfile
  package-lock.json
  package.json
Labels: dependency mgmt

#26 feature(settings): implement username with Capacitor Preferences
  package-lock.json
  package.json
  src/hooks/queries/index.ts
  src/hooks/queries/usePreferencesQueries.ts
  src/pages/home/settings/SettingsPage.tsx
  src/pages/home/settings/components/UserTab.tsx
  src/services/PreferencesService.ts
  src/services/index.ts
  src/tests/PreferencesService.test.ts
Labels: feature

#28 feat: display name in homepage greeting
  src/pages/home/HomePage.tsx
Labels: feature

#30 fix: release pipeline
  .github/workflows/release.yml
Labels: bug

#32 bug(release): fix incorrect display of graded exams in upcoming sections
  src/features/exams/ExamList.tsx
  src/pages/home/calendar/CalendarPage.tsx
Labels: bug

#34 feat: wrote tests for AppInfo.
  src/tests/AppInfo.entity.test.ts
  src/tests/__mocks__/@capacitor/capacitor.mock.ts
  src/tests/services/DataManagementService.test.ts
  src/tests/services/ExamService.test.ts
  src/tests/services/GradeService.test.ts
  src/tests/services/PreferencesService.test.ts
  src/tests/services/SchoolService.test.ts
  src/tests/services/SubjectService.test.ts
  src/tests/services/setup.ts
Labels: feature

#40 feature: Show onboarding only on first app start
  src/AppRouter.tsx
  src/hooks/queries/usePreferencesQueries.ts
  src/pages/onboarding/OnboardingPage.tsx
  src/services/DataManagementService.ts
  src/services/PreferencesService.ts
  src/tests/services/PreferencesService.test.ts
Labels: feature

#41 feat(calendar): Add modern calendar with dual view modes
  src/pages/home/calendar/CalendarPage.tsx
  src/pages/home/calendar/calendar.css
  src/pages/home/calendar/components/CalendarGrid.tsx
  src/pages/home/calendar/components/EventItem.tsx
  src/pages/home/calendar/components/ExamListView.tsx
  src/pages/home/calendar/components/MonthSelector.tsx
  src/pages/home/calendar/components/SelectedDateView.tsx
  src/pages/home/calendar/hook/useCalendar.ts
  src/pages/home/calendar/index.ts
  src/theme/variable.css
Labels: feature

#38 feat: data export
  package-lock.json
  package.json
  src/hooks/queries/useDataManagementQueries.ts
  src/services/DataManagementService.ts
Labels: feature
