Repository kevin-nca/netgrade, pull requests merged in 2025-08, with the labels that each got.

#107 fix: update back navigation to return to previous page instead of home
  src/pages/home/grades/AddGradePage.tsx
Labels: enhancement

#110 update navigation action to add exams instead of calendar
  src/pages/home/HomePage.tsx
Labels: enhancement

#125 style: add school-info class for improved styling of average grades display
  src/pages/home/HomePage.css
  src/pages/home/HomePage.tsx
Labels: style

#140 revert: missing transition animation when navigating
  package-lock.json
  package.json
  src/AppRouter.css
  src/AppRouter.tsx
  src/components/Header/Header.tsx
  src/components/PageTransition.tsx
  src/pages/home/exams/EditExamPage/EditExamPage.tsx
  src/pages/home/settings/SettingsPage.tsx
  src/theme/theme.css
Labels: bug

#57 feat(navigation): add swipe gesture and arrow key navigation support
  src/AppRouter.tsx
  src/components/navigation/EdgeSwipeBack.tsx
  src/hooks/queries/usePreferencesQueries.ts
  src/main.tsx
Labels: feature

#133 chore: add issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/pull_request_template.md
Labels: codex

#127 style: add styling for info description and update color for info title
  src/pages/home/settings/SettingsPage.css
Labels: style

#122 feat: notifications for upcoming exam
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/Info.plist
  ios/App/Podfile
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/hooks/queries/usePreferencesQueries.ts
  src/main.tsx
  src/notification-scheduler.ts
  src/pages/home/settings/SettingsPage.css
  src/pages/home/settings/SettingsPage.tsx
  src/pages/home/settings/notification/NotificationSettings.tsx
  src/services/PreferencesService.ts
Labels: feature

#158 fix: continue button layout in onboarding name step
  src/pages/onboarding/OnboardingPage.css
Labels: bug

#160 fix: ios input focus validation bug
  src/components/Form/FormField.tsx
  src/components/Form/validated-number-input/validatedNumberInput.tsx
  src/pages/home/exams/EditExamPage/components/ExamDetailsForm.tsx
  src/pages/onboarding/components/nameStep/NameStep.tsx
  src/pages/onboarding/components/subjectStep/SubjectStep.tsx
Labels: bug
